### ISSUE TITLE
ქართული NLP

### ISSUE THREAD

**Issue by alexamirejibi** [Nargizi/GNLP#1]
სალამი! სხვა საკონტაქტო ინფო ვერ ვიპოვე და აქ მივწერთქო. მეც ქართულ NLP თულებზე ვმუშაობ და თუ გექნება აზრების გაცვლის სურვილი სადმე მომწერე. კიდე 1-2 ტიპი ვიპოვე და მაგათაც მინდა მივწერო ყველას თავიდან რო არ მოგვიწიოს ქართული ენის ნიუანსების აღმოჩენა.

alexamirejibi [at] gmail.com
discord: sandman783

**Comment by alexamirejibi** [comment]
ამის წაშლას ვაპირებდი მარა ვიფიქრე იქნებ სხვასაც შეხვდეს მომწეროს, ამიტომ იყოს

**Comment by vajelski** [comment]
დიდი სიამოვნებით ვისაუბრებდი ამ თემაზე :)

**Comment by alexamirejibi** [comment]
@vajelski დისქორდზე დამამატე: sandman783
